(function(){'use strict';var cities=[],wishes=[],counts={},live=false,byId={};var province=document.getElementById('wish-province'),city=document.getElementById('wish-city'),form=document.getElementById('wish-form'),name=document.getElementById('wish-name'),content=document.getElementById('wish-content'),status=document.getElementById('wish-status'),submit=document.getElementById('wish-submit');var voterKey=localStorage.getItem('wzc-wish-voter-key')||crypto.randomUUID();localStorage.setItem('wzc-wish-voter-key',voterKey);name.value=localStorage.getItem('wzc-visitor-nickname')||'';
function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
function groupCities(){var groups={};cities.forEach(function(c){byId[c.id]=c;(groups[c.prov]=groups[c.prov]||[]).push(c)});province.innerHTML=Object.keys(groups).map(function(p){return'<option value="'+esc(p)+'">'+esc(p)+'</option>'}).join('');province.value=groups['重庆']?'重庆':Object.keys(groups)[0];province.addEventListener('change',fillCities);city.addEventListener('change',renderSelected);fillCities()}
function fillCities(){var list=cities.filter(function(c){return c.prov===province.value});city.innerHTML=list.map(function(c){return'<option value="'+c.id+'">'+esc(c.city)+'</option>'}).join('');renderSelected()}
function renderSelected(){var c=byId[city.value];document.getElementById('wish-selected').textContent=c?c.prov+' · '+c.city:'—';document.getElementById('wish-selected-count').textContent=(counts[city.value]||0)+' 次晨光'}
function renderMap(){var host=document.getElementById('wish-map-points');host.innerHTML=cities.filter(function(c){return counts[c.id]}).map(function(c){/* world-map.svg is a full Robinson-style world map: keep Chinese coordinates in the East Asia region instead of stretching them over the whole canvas */var x=Math.max(3,Math.min(97,(c.lon+180)/360*100)),y=Math.max(3,Math.min(97,(90-c.lat)/180*100)),level=Math.min(4,Math.floor(Math.log2((counts[c.id]||1)+1)));var star='<svg class="wish-star-svg" viewBox="0 0 40 40" aria-hidden="true"><circle class="star-bloom bloom-3" cx="20" cy="20" r="16"/><circle class="star-bloom bloom-2" cx="20" cy="20" r="10"/><circle class="star-bloom bloom-1" cx="20" cy="20" r="5.5"/><circle class="star-core-halo" cx="20" cy="20" r="4"/><circle class="star-core" cx="20" cy="20" r="1.65"/></svg>';return'<button type="button" data-city="'+c.id+'" class="wish-dot l'+level+'" style="left:'+x+'%;top:'+y+'%" aria-label="'+esc(c.city)+'，'+counts[c.id]+'次晨光">'+star+'<span>'+esc(c.city)+'</span></button>'}).join('');host.addEventListener('click',function(e){var b=e.target.closest('[data-city]');if(!b)return;var c=byId[b.dataset.city];province.value=c.prov;fillCities();city.value=c.id;renderSelected()})}
function renderWishes(){document.getElementById('wish-visible-count').textContent=String(wishes.length).padStart(3,'0');document.getElementById('wish-list').innerHTML=wishes.slice(0,60).map(function(w,i){var c=byId[w.city_id];return'<article class="wish-line" style="margin-left:'+([4,28,12,42,20][i%5])+'%"><span class="coord-label dim">'+(i%9===0?'✦':i%3===0?'+':'·')+' '+esc(c?c.city:'')+'</span><p>'+esc(w.content)+'</p><footer><span>'+esc(w.nickname)+'</span>'+(w.id?'<button class="coord-label dim" data-wish="'+w.id+'">◇ '+Number(w.likes||0)+'</button>':'')+'</footer></article>'}).join('')}
function applyPayload(p){wishes=p.wishes||[];counts={};(p.cityCounts||[]).forEach(function(x){counts[x.city_id]=Number(x.count)});var total=Object.keys(counts).reduce(function(n,k){return n+counts[k]},0);document.getElementById('wish-summary').textContent=total+' LIGHTS / '+Object.keys(counts).length+' CITIES';renderMap();renderSelected();renderWishes()}
Promise.all([fetch('/data/cities.json').then(function(r){return r.json()}),fetch('/api/wishes',{cache:'no-store'}).then(function(r){if(!r.ok)throw Error();live=true;return r.json()}).catch(function(){return fetch('/data/wishes-snapshot.json').then(function(r){return r.json()})})]).then(function(p){cities=p[0];groupCities();applyPayload(p[1]);if(!live){submit.disabled=true;status.textContent='HISTORICAL SNAPSHOT / 灰度祝福接口接入中，当前只读'}});
form.addEventListener('submit',function(e){e.preventDefault();if(!live)return;submit.disabled=true;status.textContent='SENDING...';var payload={nickname:name.value.trim(),content:content.value.trim(),cityId:city.value,submissionKey:voterKey,website:document.getElementById('wish-website').value};fetch('/api/wishes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.json().then(function(j){if(!r.ok)throw Error(j.error);return j})}).then(function(){localStorage.setItem('wzc-visitor-nickname',payload.nickname);content.value='';status.textContent='✦ 已送达，审核通过后会出现在这里'}).catch(function(){status.textContent='暂时没有送达，请稍后再试'}).finally(function(){submit.disabled=false})});
document.getElementById('wish-list').addEventListener('click',function(e){var b=e.target.closest('[data-wish]');if(!b||!live)return;fetch('/api/wishes',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:Number(b.dataset.wish),voterKey:voterKey})}).then(function(r){return r.json()}).then(function(x){if(x.likes!=null)b.textContent='✦ '+x.likes})})})();
